name: 'Github Actions Respository Secret Manager'
author: 'kerridge'
description: 'A tool to create|update|delete encrypted repository secrets in github actions.'
inputs:
  action:
    description: 'The action to be performed. `create`, `update`, or `delete`'
    mandatory: True
  token: 
    description: 'A GitHub Personal Access Token with manage secrets permission. Can NOT be the GITHUB_TOKEN secret.'
    mandatory: True
  name:
    description: 'The secret name to apply the action to'
    mandatory: True
  value:
    description: 'A quote encapsulated secret value. Only required if `create` or `update` is selected'
    mandatory: False
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    ACTION: ${{ inputs.action }}
    TOKEN: ${{ inputs.token }}
    NAME: ${{ inputs.name }}
    VALUE: "${{ inputs.value }}"
branding:
  icon: 'lock'  
  color: 'blue'